### ISSUE TITLE
Problem with median

### ISSUE THREAD

**Issue by byaka** [cxxr/LiveStats#4]
`[1, 5, 6, 7, 9, 12, 15, 19, 20]`
for this set LiveStats shows me `8.68209876543` but this is not a median for this values! It's not just not-accurate - this just not a median. Just becouse median must split set to 2 parts with same length, this value **wrong**.
Any ideas why this happened and how to solve this?

**Comment by cxxr** [comment]
The median given by LiveStats is not exact, but approximate. The exact median in this data set, `9`, is fairly close to the approximate median estimated by LiveStats at `8.6`. 

If you need an exact median, I would recommend using a traditional median finding algorithm. LiveStats is meant to be used when those algorithms are too expensive and the exact median is not required.
